### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by dcanulr** [AltamarMx/plantilla-tesis-latex-ier#4]
Agregar recomendaciones/trips/consejos/trucos para crear tablas, por ejemplo, dividir tablas para varias páginas, o que se ajuste una tabla demasiado ancha a una página

**Comment by AltamarMx** [comment]
Se agreg'o una secci'on con 3 tablas, una tabla sencilla, una tabla rotada en una p'agina, y una tabla muuuy larga.
